sudo: false

language: java

jdk:
  - oraclejdk8

before_script:
  - mysql -u root < project-resources/init-mysql.sql
  - psql -U postgres -f project-resources/init-psql.sql

install:
  - ./gradlew assemble

script:
  - ./gradlew check -Pintegration


env:
  global:
    - secure: "DcgB1wHDG1GiFZukDbUnHctE9iA1GogSyIqtsVnPdtVa9OelkVMtb7uVeb1S/X02rjGhrI8f1VGZ6Vqnm8+Uvqf91lMPrpn5/EBQ9LOUJEIqDErXswAWQTSa4yxwAhUGE99eI9pglxh40dAGmDhrKe7Lq1lnQbr3IGUrYgnolLw=" 
